services:
  adminer:
    profiles: ["stage", "dev"]
    image: adminer:4.8.1
    container_name: musmgr-adminer
    networks:
      - musmgr
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - ${ADMINER_PORT:-8080}:8080

  postgres:
    profiles: ["stage", "dev"]
    build: backend/db/.
    container_name: musmgr-db
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - musmgr
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  svelte:
    profiles: ["stage"]
    build: frontend/.
    container_name: musmgr-frontend
    environment:
      VITE_BACKEND_HOST: ${BACKEND_HOST:-go-gin}
      VITE_BACKEND_PORT: ${BACKEND_PORT:-8000}
    ports:
      - 5173:3000
    networks:
      - musmgr

  go-gin:
    profiles: ["stage", "dev"]
    build: backend/.
    container_name: musmgr-backend
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      BACKEND_HOST: ${BACKEND_HOST:-go-gin}
      BACKEND_PORT: ${BACKEND_PORT:-8000}
      # GIN_MODE: release
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - musmgr

networks:
  musmgr:
    driver: bridge
